<a href="https://colab.research.google.com/github/abhijith00710-coder/Pandas/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PANDAS**

Dataset


dataframe(df) - data into row column form,
                ndim=2,
                
series -building block of dataframe

dimension of element in a data frame is 0

diff between series and array

array

*   implicit indexing
*   for data storing less memory
*   faster
*   n dimension






series

*   Explicit indexing
*   for data storing more memory
*   slower
*   only one dimension

In [ ]:
import pandas as pd
import numpy as np
a=np.arange(4,10)

s=pd.Series(a)

print(s)

print(s.ndim)
print(s.shape)
print(s.size)

#for getting initial rows up to range

print(s.head) # normally 5
print(s.head(4))

# for getting funal rows

print(s.tail(3))

0    4
1    5
2    6
3    7
4    8
5    9
dtype: int64
1
(6,)
6
<bound method NDFrame.head of 0    4
1    5
2    6
3    7
4    8
5    9
dtype: int64>
0    4
1    5
2    6
3    7
dtype: int64
3    7
4    8
5    9
dtype: int64

In [ ]:
# create two series

a=pd.Series([4,5,6,7,8])

b=pd.Series([5,4,3,6,7])

# print(a)
# print(b)

# conactenate two series

d=pd.concat([a,b],ignore_index=True) # ignore index koduthillel pazhaya index
                                     # show chyum athil
print(d)

0    4
1    5
2    6
3    7
4    8
5    5
6    4
7    3
8    6
9    7
dtype: int64

In [ ]:
# Adding two series

e=a.add(b)
print(e)

0     9
1     9
2     9
3    13
4    15
dtype: int64

In [ ]:
# Subtracting two series

e=a.sub(b)
print(e)

0   -1
1    1
2    3
3    1
4    1
dtype: int64

In [ ]:
# Multiplyng two series

e=a.mul(b)
print(e)

0    20
1    20
2    18
3    42
4    56
dtype: int64

In [ ]:
# dividing two series

e=a.div(b)
print(e)

0    0.800000
1    1.250000
2    2.000000
3    1.166667
4    1.142857
dtype: float64

In [ ]:
# for custom indexing use , index function and mention the custom index you want to print

z=pd.Series([3,4,5,6],index=["a","b","c","d"])
print(z)

a    3
b    4
c    5
d    6
dtype: int64

In [ ]:
d={"id":1,"age":54,"class":"ds"}

z=pd.Series(d)
print(z)  # here key become index of that

id        1
age      54
class    ds
dtype: object

In [ ]:
z=pd.Series(4,index=[1,2,3,4])
z

1    4
2    4
3    4
4    4
dtype: int64

In [ ]:
z=pd.Series([1,2,3,4,5,6,7])

print(z)

z[3]

z[1:4]

z[[6,1,5]]  # seperate index mathram edukkan coma ettu double
            # closed bracket il aakkuka

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

6    7
1    2
5    6
dtype: int64

**DATA FRAME**

In [ ]:
# creating a data frame from list

l=[1,2,3,4,5]

df=pd.DataFrame(l)

df

df.shape

df.size

df.ndim

2

In [ ]:
# creating data frame from nested list

l=[["apple",102],["orange",48],["grapes",56]]

df=pd.DataFrame(l,columns=["fruits","price"])
df

   fruits  price
0   apple    102
1  orange     48
2  grapes     56

In [ ]:
# create a dataframe with id name and locasion and add 4 rows

l=[[1,"abhi","tvm"],[2,"ashik","kottayam"],[3,"aseem","tvm"],[4,"abhijith","tvm"]]

df=pd.DataFrame(l,columns=["id","name","location"])

df

   id      name  location
0   1      abhi       tvm
1   2     ashik  kottayam
2   3     aseem       tvm
3   4  abhijith       tvm

In [ ]:
# using dictionary and list above problem

d={"id":[1,2,3,4],"name":["abi","ram","shekhar","jack"],"age":[20,23,23,22]}

df=pd.DataFrame(d)

df

   id     name  age
0   1      abi   20
1   2      ram   23
2   3  shekhar   23
3   4     jack   22

In [5]:
import pandas as pd

# creating data frame from list of dictionaries

l=[{"fruits":"apple","price":234},{"fruits":"orange","price":87},
 {"fruits":"grapes","price":90}]

df=pd.DataFrame(l)

df

   fruits  price
0   apple    234
1  orange     87
2  grapes     90

In [9]:
# Cretaing dataframe using dictionary and series

d={"fruits":pd.Series(["apple","orange","mango"]),"price":pd.Series([235,89,76])}

df=pd.DataFrame(d)
df

   fruits  price
0   apple    235
1  orange     89
2   mango     76

In [14]:
# Create a dataframe with id name age salary profession and add 5 values

dl={"id":[1,2,3,4,5],"name":["abhi","ashik","aseem","siva","henna"],
   "age":[20,21,22,21,23],"salary":[10000,12000,20000,20000,21000],
   "profession":["data analyst","business analyst","QA","erp","hr"]}

df=pd.DataFrame(dl)
df

nl=[[1,2,3,4,5],["abhi","ashik","aseem","siva","henna"],[20,21,22,21,23]
    ,[10000,12000,20000,20000,21000],
     ["data analyst","business analyst","QA","erp","hr"]]

dfnl=pd.DataFrame(nl,columns=["id","name","age","salar","proff"])

dfnl

             id              name    age  salar  proff
0             1                 2      3      4      5
1          abhi             ashik  aseem   siva  henna
2            20                21     22     21     23
3         10000             12000  20000  20000  21000
4  data analyst  business analyst     QA    erp     hr

In [16]:
# Adding new elementto a dataframe

print(dfnl)

# adding new column similarway we add new element to a dictionary

dfnl["gender"]=["M","M","M","M","F"]

dfnl

             id              name    age  salar  proff
0             1                 2      3      4      5
1          abhi             ashik  aseem   siva  henna
2            20                21     22     21     23
3         10000             12000  20000  20000  21000
4  data analyst  business analyst     QA    erp     hr

             id              name    age  salar  proff gender
0             1                 2      3      4      5      M
1          abhi             ashik  aseem   siva  henna      M
2            20                21     22     21     23      M
3         10000             12000  20000  20000  21000      M
4  data analyst  business analyst     QA    erp     hr      F

In [18]:
# To display a particular column

dfnl[["name"]]

dfnl[["name","gender"]]

               name gender
0                 2      M
1             ashik      M
2                21      M
3             12000      M
4  business analyst      F